<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/glide.core.css">
    <link rel="stylesheet" href="css/glide.core.min.css">
    <link rel="stylesheet" href="css/glide.theme.css">
    <link rel="stylesheet" href="css/glide.theme.min.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta charset="utf-8">
    <title>Eat the sun</title>
  </head>
  <body>
    <?php
include 'header.php' ?>
    <main>

      <section id="intro">
<video muted autoplay loop  id="intro-vid">
  <source src="video/video.mp4" type="video/mp4">
</video>

        <div class="slogan fadein">
          <h1>beauty & life style</h1>
          <h3>learn with us how to take care of your face</h3>
        </div>
      </section>
      <section class="container" id="about">
        <h2>about</h2>
        <div class="col-left-about">
          <p><span> Beauty&Lifestyle,</span> founded by Jane Doe in April 2020, is an online platform to provide educational courses to the public.</p>
          <p>The purpose of the company is to educate people how to live a natural lifestyle with better eating habits, with better self-care habits and more physical movement.</p>
          <p class="bt-in"><button type="button" class="btn" name="button">read more</button></p>
        </div>

        <div class="col-right-about">
<img class="img-responsive" src="images/photo-1522108098940-de49801b5b40.png"alt="">
        </div>
      </section>
      <div class="wave"></div>
      <section id="proj">
        <div class="container">
          <h2>Online Projects</h2>
<div class="col-left-proj">
  <h3>Face Studio</h3>
  <p>An online platform to provide you with guidance on how to look after your beauty with the most natural methods!</p>
  <p>Face Studio will help you release, repair and renew your face as well as add more confidence, radiance and glow to your presence through facial exercises, massage techniques, the right diet and much more!</p>
  <p>Visit at the link below, choose the level you want to commit to and start your journey with us!</p>
  <p class="bt-out"><button type="button" class="btn"name="button">Read more</button></p>
</div>
<div class="col-right-proj">
  <h3>Jane Doe Lifestyle</h3>
  <p>Lifestyle habits can build the health and success of one’s life. However, many are not fully aware between the difference of positive and negative habits, and their impact on physical and emotional well-being. Beauty&Lifestyle and the founder Jane Doe, a certified Health Coach, offer you to take your life into control and learn the best tricks and tips through the courses and consultations available online.</p>
<p>Visit the link below for private coaching programs and say YES to living your best life!</p>
  <p class="bt-out"><button type="button" class="btn" name="button">Read more</button></p>
</div>
</div>
      </section>
      <section class="container" id="form">
        <h2>Contact us!</h2>
        <div class="col-left-form">
          <form action="index.html" method="post">
          <p><input type="text" name="name" placeholder="Your Name"></p>
          <p><input type="text" name="" placeholder="Your Email"></p>
          <p><textarea name="" placeholder="Your message" rows="8" cols="40"></textarea></p>
          </form>
          <p class="but-down"><button type="button" class="btn-form" name="button">submit</button></p>
        </div>
<div class="col-right-form">
    <img class="img-responsive" src="images/hello.png" alt="">
</div>

      </section>




</main>
<?php
include 'footer.php'
 ?>
<script src="js/main.js"></script>
</body>
</html>
