<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"
    <meta charset="utf-8">
    <title>Eat the sun</title>
  </head>
  <body>
<?php
include 'header.php'
 ?>
    <main>
      <section id="present">
        <div class="fadein">
          <h1>Our Story</h1>
          <h3>Comme with us and illuminate from within</h3>
        </div>
      </section>
      <section class="container" id="lifestyle">
        <div class="col-left-lifestyle">
            <p><strong> Beauty&Lifestyle,</strong> founded by Jane Doe in April 2020, is an online platform to provide educational courses to the public.founded by Jane Doe in April 2020, is an online platform to provide educational courses to the public.</p>
            <p><strong>The purpose of the company</strong>is to educate people how to live a natural lifestyle with better eating habits, with better self-care habits and more physical movement.</p>

        </div>

        <div class="col-right-lifestyle">
          <img class="img-responsive" src="images/influencer2@2x.PNG" alt="">
          <div class="blue-circle-1"></div>
          <div class="blue-circle-2"></div>
      </section>
      <div class="wave"></div>
      <section id="circle">
        <div class="container">
            <h2>The Message</h2>

          <p><strong>The message is in the name.</strong> Beauty&Lifestyle represents the following ideas and philosophies:</p>

          <div class="blue-circle-3"><p>Beauty&Lifestyle by spending more active time outside</p></div>
          <div class="blue-circle-4"><p>Beauty&Lifestyle by spending more active time outside</p></div>
          <div class="blue-circle-5"><p>Beauty&Lifestyle by spending more active time outside</p></div>
          <div class="blue-circle-6"><p>Beauty&Lifestyle by spending more active time outside</p></div>

        </div>

      </section>
      <section class="container" id="idea">
        <h2>Keeping all the ideas in one place…</h2>
        <p>The online portal provides with various courses that encourage, educate and support people to trigger new habits, bring them closer to nature and to a deeper balance within.</p>
        <div class="col-left-idea">
<h1>The Face Studio</h1>
<p><strong>One of the main projects under Beauty&Lifestyle – is Face Studio</strong>– an online platform providing courses to learn and practice facial exercises, facial self- massage techniques, tips on skincare routine and products.</p>

        </div>
        <div class="col-right-idea">
          <img class="img-responsive" src="images/2_faces@2x.png" alt="">
          <div class="blue-circle-7"></div>
          <div class="blue-circle-8"></div>
        </div>
      </section>
      <section class="container" id="grapes">
        <div class="col-left-grapes">
        <img class="img-responsive" src="images/grapes@2x.PNG" alt="">
        <div class="blue-circle-9"></div>
        <div class="blue-circle-10"></div>
        </div>
        <div class="col-right-grapes">
          <h1>Jane Doe Lifestyle</h1>
          <p><strong>One of the main projects under Beauty&Lifestyle – is Face Studio</strong>– an online platform providing courses to learn and practice facial exercises, facial self- massage techniques, tips on skincare routine and products.</p>
        </div>
        <div class="grape">
          <p><span>Beauty&Lifestyle</span> looks forward to setting up more projects and launching more online courses which will transform the lives of many.</p>

        </div>
      </section>


</main>
<?php
include'footer.php' ?>
<script src="js/main.js"></script>
</body>
</html>
